### ISSUE TITLE
Scope with arguments and chain it's not working with paranoid2

### ISSUE THREAD

**Issue by loureirorg** [anjlab/paranoid2#3]
Scope with arguments and chain it's not working with paranoid2.

**Steps to reproduce the problem:**

_create a table "user" with an "email" field:_

``` shell
 rails g scaffold User email:string
```

_put this scope in the model:_

``` ruby
class User < ActiveRecord::Base
  paranoid
  scope :find_last, lambda { |email| where(email: email).last }
end
```

_on "rails console":_

``` ruby
Loading development environment (Rails 4.0.0)
irb(main):001:0> User.find_last "some@email.com"
  User Load (0.4ms)  SELECT "users".* FROM "users" WHERE "users"."deleted_at" IS NULL AND "users"."email" = 'some@email.com' ORDER BY "users"."id" DESC LIMIT 1
  User Load (0.1ms)  SELECT "users".* FROM "users" WHERE "users"."deleted_at" IS NULL
=> #<ActiveRecord::Relation []>
```

**What's the expected result?**
Just one SELECT query (the first one):

``` sql
SELECT "users".* FROM "users" WHERE "users"."deleted_at" IS NULL AND "users"."email" = 'some@email.com' ORDER BY "users"."id" DESC LIMIT 1
```

**What happens instead?**
2 queries: with the second invalidating the first

**Comment by yury** [comment]
Thank you for your response.

But you are misusing scope. Scope should always return `Relation` object, not `Model` object. (In your case `last` one)

What is happening in your case:
https://github.com/rails/rails/blob/master/activerecord/lib/active_record/scoping/named.rb#L148

`scope || all` cause to execute first (correct scope), if it returns nil, it returns `all` scope

You should simply use plain static method method:

``` ruby
def self.find_last email
  where(email: email).last
end
```

**Comment by loureirorg** [comment]
ops. My bad. Sorry for this :P

**Comment by yury** [comment]
no problem
