### ISSUE TITLE
belongs_to and with_deleted

### ISSUE THREAD

**Issue by Curter29** [anjlab/paranoid2#4]
Hello i use Rails 4, a have next code:

```
User 
 belongs_to :city
end

City
 paranoid
 has_many :users
end
```

hot to get User.find(N).city if city is soft-destroyed?

**Comment by DmitryTsepelev** [comment]
You included `paranoid` to City model so you have `only_deleted` and `with_deleted` scope methods (look [here](https://github.com/anjlab/paranoid2/blob/master/lib/paranoid2/scoping.rb)).

You should override `city` method in your User model this way:

``` ruby
def city
   City.with_deleted.where(id: city_id).first
end
```

It will return your user city even if it was deleted.

**Comment by Curter29** [comment]
But in this case, if make

```
User.all.each do |u|
 u.city # fire one SELECT per user
end
```

Exist any other method to use like `User.incldes(:city)` ?

**Comment by yury** [comment]
Hmm, only way for now is to merge relations:

``` ruby
User.includes(:city).merge(City.with_deleted).references(:city).each do |u|
  u.city 
end
```

**Comment by Curter29** [comment]
Thanks a lot, i will try this in future.
